language: java
jdk:
  - openjdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "jlp6yfab3wdv1leumyzodfbqoqdxz4n7"
    token:
      secure: "43092d8fe6ff5c19a7ecec981f4a5ea618fb3024"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
