spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traveldb
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create

jwt:
  secret: travelManager_Key
  #expiration = 7 days
  expiration: 604800
