spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traveldb?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: travel-manager-api

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

server:
  port: 8080

jwt:
  secret: travelManager_KeyJWT@20191129
  # 1 DIA
  expirationInMs: 86400000

# 30 MINUTOS
# expirationInMs = 1800000
# 1 MINUTO
# expirationInMs = 60000

